language: ruby
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/rails_4_mysql2_driver.gemfile
  - gemfiles/rails_4_pg_driver.gemfile
  - gemfiles/rails_4_sqlite3_driver.gemfile
before_script:
  - "mysql -e 'create database pacecar_test;' >/dev/null"
  - "psql -c 'create database pacecar_test;' -U postgres >/dev/null"
  - "cd spec/dummy && RAILS_ENV=test bundle exec rake db:migrate && cd -"
