language: ruby
rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/rails-3.0.17-database-mysql.gemfile
  - gemfiles/rails-3.0.17-database-mysql2.gemfile
  - gemfiles/rails-3.0.17-database-pg.gemfile
  - gemfiles/rails-3.0.17-database-sqlite3.gemfile
  - gemfiles/rails-3.1.8-database-mysql.gemfile
  - gemfiles/rails-3.1.8-database-mysql2.gemfile
  - gemfiles/rails-3.1.8-database-pg.gemfile
  - gemfiles/rails-3.1.8-database-sqlite3.gemfile
  - gemfiles/rails-3.2.8-database-mysql.gemfile
  - gemfiles/rails-3.2.8-database-mysql2.gemfile
  - gemfiles/rails-3.2.8-database-pg.gemfile
  - gemfiles/rails-3.2.8-database-sqlite3.gemfile
before_script:
  - "mysql -e 'create database pacecar_test;' >/dev/null"
  - "psql -c 'create database pacecar_test;' -U postgres >/dev/null"
  - "cd spec/dummy && RAILS_ENV=test bundle exec rake db:migrate && cd -"
